# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "webby"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: '127.0.0.1'

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'webby'
    vb.memory = 2048
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "files/install.nginx.sh"
  config.vm.provision "shell", path: "files/disable.banner.sh"
  config.vm.provision "shell", name: "tools", path: "files/install.tools.sh"
end
